### ISSUE TITLE
Data Collection Broken from recent firmware update?

### ISSUE THREAD

**Issue by martyp187** [potchin/plusnet_monitoring#1]
The container exits with the error log below.

Traceback (most recent call last):
  File "/usr/src/app/./monitor.py", line 151, in <module>
    main()
  File "/usr/src/app/./monitor.py", line 143, in main
    output_data = get_data_from_router()
  File "/usr/src/app/./monitor.py", line 48, in get_data_from_router
    r.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://192.168.1.254/nonAuth/wan_conn.xml

Viewing this link in a browser doesn't work and does indeed get a 403 error.

A google suggests a change in the firmware and a user on the plusnet forum has worked around this in their script by making the request with a specific header.

The post mentions..

> "Previously I was grabbing the page into my script with:
> 
>    curl --silent http://192.168.1.254/nonAuth/wan_conn.xml -H "Accept: application/xml"
> 
> but that no longer works.
> 
> I have now found that if I include a referrer (I don't know why it needs that header, but it does), I can grab the XML file OK. So I've amended my script this, and now it's working again:
> 
>    curl --silent http://192.168.1.254/nonAuth/wan_conn.xml -H "Referer: http://192.168.1.254/basic_-_status.htm" -H "Accept: application/xml"
   
   Are you able to fix @potchin ?

**Comment by potchin** [comment]
Should be good now, just re-pull the `latest` image
